version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    environment:
      - MONGO_URL=mongodb://mongodb:27017/mydb
    ports:
      - "7004:7004"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:8
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge