version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    environment:
      - MONGO_URL=mongodb://127.0.0.1:27017/apiflow
    ports:
      - "7004:7004"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:8
    volumes:
      - mongodb_data:/data/db
    environment:
      # 本地部署需要替换成你的mongod用户名和密码 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: xQ3!p8L*9zR6#vN2 
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge