name: Build Windows App

# 触发条件：创建tag时或手动触发
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: v1.0.0)'
        required: false
        default: 'manual-build'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Node.js环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: 安装依赖
        run: npm ci
        
      - name: 构建前端应用
        run: npm run web:build:web
        
      - name: 打包Windows应用
        run: npm run web:build:standalone:win
        env:
          # 禁用代码签名（如果需要签名，请配置相关证书）
          CSC_IDENTITY_AUTO_DISCOVERY: false
          
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: apiflow-windows
          path: |
            packages/web/release/*.exe
            packages/web/release/*.zip
          retention-days: 30
          
  # 创建GitHub Release（仅在推送tag时执行）
  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-windows
    runs-on: ubuntu-latest
    
    steps:
      - name: 下载所有构建产物
        uses: actions/download-artifact@v4
        
      - name: 创建Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            apiflow-windows/*
          tag_name: ${{ github.ref_name }}
          name: Apiflow ${{ github.ref_name }}
          body: |
            ## 📦 Windows版本下载
            
            ### 安装版
            - **Windows x64**: `Apiflow-*-x64.exe`
            - **Windows ARM64**: `Apiflow-*-arm64.exe`
            
            ### 便携版
            - **Windows x64**: `Apiflow-*-x64.zip`
            - **Windows ARM64**: `Apiflow-*-arm64.zip`
            
            ## 🚀 更新内容
            
            请查看提交记录了解详细更改。
            
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}